CmdOnOffOderList = {

	"/notrade", 
	"/noshift", 
	"/noctrl", 
	"/skillfail", 
	"/notalkmsg", 
	"/notalkmsg2", 
	"/showname", 
	"/fog", 
	"/aura", 
	"/window", 
	"/miss", 
	"/q1", 
	"/q2", 
	"/effect", 
	"/bgm", 
	"/sound", 
	"/loginout", 
	"/shopping", 
	"/stateinfo", 
	"/snap", 
	"/itemsnap", 
	"/skillsnap", 
	"/hoai", 
	"/merai", 
	"/camera", 
	"/btg"
}
CmdOnOffList = {

	["/battlemode"] = 1,
	["/notrade"] = 1,
	["/noshift"] = 1,
	["/noctrl"] = 0,
	["/skillfail"] = 1,
	["/notalkmsg"] = 1,
	["/notalkmsg2"] = 1,
	["/showname"] = 1,
	["/fog"] = 1,
	["/aura"] = 1,
	["/window"] = 1,
	["/miss"] = 1,
	["/q1"] = 0,
	["/q2"] = 0,
	["/effect"] = 1,
	["/bgm"] = 1,
	["/sound"] = 1,
	["/loginout"] = 1,
	["/shopping"] = 1,
	["/stateinfo"] = 1,
	["/snap"] = 0,
	["/itemsnap"] = 0,
	["/skillsnap"] = 1,
	["/hoai"] = 0,
	["/merai"] = 0,
	["/camera"] = 0,
	["/btg"] = 1
}
CmdHelpList = {
	--Orderlist Desc Start
	["/battlemode"] = "/battlemode : Allows you to use skills assigned to Shortcut Window 2 by pressing Q ~ O keys.",
	["/notrade"] = "/notrade : Declines trade offers automatically. On | Off",
	["/noshift"] = "/noshift : You may use your ''force heal'' ability without the Shift key. On | Off",
	["/noctrl"] = "/noctrl : Auto attack without pressing ctrl key. On | Off",
	["/skillfail"] = "/skillfail : Display red font message when skill fails. On | Off",
	["/notalkmsg"] = "/notalkmsg : Chat will not be displayed in chat window. On | Off",
	["/notalkmsg2"] = "/notalkmsg2 : Hides chat messages(including guild chat). On | Off",
	["/showname_on"] = "Normal Font Displayed. [showname type 1]",
	["/showname_off"] = "Font will be thin and party name will be shown [showname type 2]",
	["/fog"] = "/fog : Fog effect. On | Off",
	["/aura"] = "/aura : Simplify Aura effect On | Off",
	["/window"] = "/window : Display windows will snap/dock together. On | Off",
	["/miss"] = "/miss : Toggle ''Miss'' display",
	["/q1"] = "/quickspell  : Right-click menu enables you to use skills assigned to the F9 hotkey. On | Off",
	["/q2"] = "/quickspell2 : By rolling the mouse wheel up and down, you are able to use skills registered on F7 and F8 hotkeys. On | Off",
	["/effect"] = "/effect : Effects On | Off",
	["/bgm"] = "/music : Turns BGM On | Off",
	["/sound"] = "/sound: Turns Sound Effects On | Off",
	["/loginout"] = "/loginout : Shows guildsmen and friends online status. On | Off",
	["/shopping"] = "/shopping : Enables you to open a shop with a single left-click and close your shop with a single right-click. On | Off",
	["/stateinfo"] = "/stateinfo : Shows a description of the status icons. On | Off",
	["/snap"] = "/snap : Turns the snap On | Off for monsters.",
	["/itemsnap"] = "/itemsnap : Turns snap On | Off for items on the grounds.",
	["/skillsnap"] = "/skillsnap : Turns snap On | Off for skills.",
	["/hoai"] = "/hoai : Toggles custom homunculus AI. On | Off",
	["/merai"] = "/merai : Toggles custom mercenary AI. On | Off",
	["/camera"] = "/camera : Toggles between smooth/locked camera. On | Off",
	["/btg"] = "/btg : Toggles battleground icons. On | Off",
	--Orderlist Desc End
	["/taekwon"] = "Taekwon Rank",
	["/munak"] = "Taiming Rank",
	["/death"] = "Death Knight Rank",
	["/collector"] = "Collector Rank",
	["/hi"] = "/hi or /hi message: Send greetings to people who are online and registered on your Friend List.",
	["/blacksmith"] = "/blacksmith : Shows top 10 Blacksmiths in the server.",
	["/alchemist"] = "/alchemist : Shows top 10 Alchemists in the server.",
	["/help"] = "/h or /help : Shows this Command Help List",
	["/who"] = "/w or /who : Shows the number of current players connected.",
	["/sit"] = "/sit : Sit command. If you are sitting, you will stand instead.",
	["/stand"] = "/stand : Stand command. If you are standing, you will sit instead.",
	["/q"] = "/q : Leaves a Chat Room",
	["/leave"] = "/leave : Leaves a party",
	["/where"] = "/where : Shows your present location",
	["/memo"] = "To memorize a place as Warp Point (If you are an Acolyte Class character)",
	["/chat"] = "/chat : Creates a Chat Room",
	["/savechat"] = "/savechat : Save a Chat Log",
	["/doridori"] = "/doridori : Shake head ^^;;",
	["/bangbang"] = "/bingbing : Rotates player counter clockwise. ^^;;",
	["/bingbing"] = "/bangbang : Rotates player clockwise. ^^;;",
	["/ex"] = "/ex : View a list of Characters you have Blocked.",
	["/inall"] = "Allows whispers from anyone",
	["/exall"] = "Blocks whispers from everyone.",
	["/pvpinfo"] = "/pvpinfo : Shows your PVP result and PVP points.",
	["/hunting"] = "/hunting : You can check the your hunting list."
}
OptionInfoList = {

	["Window_XPos"] = -1,
	["Window_YPos"] = -1,
	["Trilinear"] = 0,
	["Bgm_Volume"] = 100,
	["Effect_Volume"] = 100,
	["AutoOpen1to1Window"] = 1,
	["AutoOpen1to1Window_Friend"] = 1,
	["PlaySound_Open1to1Window"] = 1,
	["Simplicity_SkillList"] = 0,
	["Show_SkillDescript"] = 0,
	["ChangeChatMode"] = 1,
	["LockMouse"] = 0,
	["ChannelCopID"] = 0,
	["Outdoor_ViewLatitude"] = -45,
	["Outdoor_ViewDistance"] = 300,
	["Indoor_ViewLatitude"] = -45,
	["Indoor_ViewDistance"] = 300,
	["SkinName"] = "<Basic Skin>"
}