PRIORITY_RED = 0
PRIORITY_BLUE = 1
PRIORITY_GREEN = 2
PRIORITY_WHITE = 3
StateIconImgList = {

	[PRIORITY_RED] = {
		[EFST_IDs.EFST_HANDICAPSTATE_NORECOVER] = "NORECOVER.TGA",
		[EFST_IDs.EFST_EXTREMITYFIST] = "EXTREMITYFIST.TGA"
	},

	[PRIORITY_BLUE] = {
		[EFST_IDs.EFST_SET_NUM_DEF] = "SETDEF.TGA",
		[EFST_IDs.EFST_SET_PER_DEF] = "SETDEF.TGA"
	},

	[PRIORITY_GREEN] = {
		[EFST_IDs.EFST_SET_NUM_MDEF] = "SETMDEF.TGA",
		[EFST_IDs.EFST_SET_PER_MDEF] = "SETMDEF.TGA"
	},

	[PRIORITY_WHITE] = {

	},

}