PRIORITY_RED = 0
PRIORITY_BLUE = 1
PRIORITY_GREEN = 2
PRIORITY_WHITE = 3
StateIconImgList = {

	[PRIORITY_RED] = {
		[EFST_IDs.EFST_HANDICAPSTATE_NORECOVER] = "NORECOVER.TGA",
		[EFST_IDs.EFST_EXTREMITYFIST] = "EXTREMITYFIST.TGA",
		[EFST_IDs.EFST_GM_BATTLE] = "ICON02.TGA",
		[EFST_IDs.EFST_GM_BATTLE2] = "ICON02.TGA",
		[EFST_IDs.EFST_KG_KAGEHUMI] = "KG_KAGEHUMI.TGA",
		[EFST_IDs.EFST_KYOMU] = "KYOMU.TGA",
		[EFST_IDs.EFST_AKAITSUKI] = "AKAITSUKI.TGA"
	},

	[PRIORITY_BLUE] = {
		[EFST_IDs.EFST_ATTHASTE_CASH] = "ASPDCASH.TGA",
		[EFST_IDs.EFST_2011RWC] = "ELDICASTES.TGA",
		[EFST_IDs.EFST_2011RWC_SCROLL] = "RWCSCROLL.TGA",
		[EFST_IDs.EFST_MYSTICPOWDER] = "MYSTICPOWDER.TGA",
		[EFST_IDs.EFST_M_LIFEPOTION] = "소형생명수.TGA",
		[EFST_IDs.EFST_FLOWER_LEAF] = "FLOWER_LEAF.TGA",
	},

	[PRIORITY_GREEN] = {
		[EFST_IDs.EFST_SET_NUM_DEF] = "SETDEF.TGA",
		[EFST_IDs.EFST_SET_PER_DEF] = "SETDEF.TGA",
		[EFST_IDs.EFST_SET_NUM_MDEF] = "SETMDEF.TGA",
		[EFST_IDs.EFST_SET_PER_MDEF] = "SETMDEF.TGA"
	},

	[PRIORITY_WHITE] = {
		[EFST_IDs.EFST_ZANGETSU] = "ZANGETSU.TGA",
		[EFST_IDs.EFST_GENSOU] = "GENSOU.TGA",
		[EFST_IDs.EFST_PHI_DEMON] = "PHIDEMON.TGA",
		[EFST_IDs.EFST_MEIKYOUSISUI] = "MEIKYOUSISUI.TGA",
		[EFST_IDs.EFST_IZAYOI] = "IZAYOI.TGA",
		[EFST_IDs.EFST_KAGEMUSYA] = "KAGEMUSYA.TGA"
	},

}