RobeNameTable = {
	[SPRITE_ROBE_IDs.ROBE_WINGS] = "천사날개",
	[SPRITE_ROBE_IDs.ROBE_BAG_OF_ADVENTURER] = "모험가배낭",
	[SPRITE_ROBE_IDs.ROBE_WINGS_OF_FALLEN_ANGEL] = "타락천사의날개",
}

RobeNameTable = {
	[SPRITE_ROBE_IDs.ROBE_WINGS] = "ANGEL_WINGS",
	[SPRITE_ROBE_IDs.ROBE_BAG_OF_ADVENTURER] = "BAG_OF_ADVENTURER",
	[SPRITE_ROBE_IDs.ROBE_WINGS_OF_FALLEN_ANGEL] = "WINGS_OF_FALLEN_ANGEL",
}